# -*- coding: utf-8 -*-
"""MobileNetV2_Student_Engagement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3hxcCAvsKXUkjwq--qoBgRMQVOB4R5r

## ✅ STEP 1 — Mount Drive & Import Libraries
"""

# Mount Google Drive so we can read your zip file
from google.colab import drive
drive.mount('/content/drive')
print('✅ Drive mounted')

# Install / import everything we need
import os, shutil, zipfile, random
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import (EarlyStopping,
                                         ReduceLROnPlateau,
                                         ModelCheckpoint)
from sklearn.metrics import classification_report, confusion_matrix

print('TensorFlow:', tf.__version__)
print('GPU available:', tf.config.list_physical_devices('GPU'))
print('✅ All libraries ready')

"""## ✅ STEP 2 — Extract Dataset"""

ZIP_PATH     = '/content/drive/MyDrive/archive.zip'

EXTRACT_PATH = '/content/raw_dataset'

print('📦 Extracting zip…')
with zipfile.ZipFile(ZIP_PATH, 'r') as z:
    z.extractall(EXTRACT_PATH)
print('✅ Extraction done!\n')

# Auto-detect structure so we can verify paths
for root, dirs, files in os.walk(EXTRACT_PATH):
    level = root.replace(EXTRACT_PATH, '').count(os.sep)
    imgs  = [f for f in files if f.lower().endswith(('.jpg','.jpeg','.png'))]
    print('  ' * level + os.path.basename(root) + f'/  → {len(imgs)} images')

"""# 📊 STUDENT ENGAGEMENT DATASET — FULL VISUAL ANALYSIS"""

import os, random
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec
from PIL import Image
import warnings
warnings.filterwarnings('ignore')

# ── Dataset paths ──────────────────────────────────────────
EXTRACT_PATH = '/content/raw_dataset'
SOURCE_CLASSES = {
    'engaged':      f'{EXTRACT_PATH}/Student-engagement-dataset/Engaged/engaged',
    'confused':     f'{EXTRACT_PATH}/Student-engagement-dataset/Engaged/confused',
    'frustrated':   f'{EXTRACT_PATH}/Student-engagement-dataset/Engaged/frustrated',
    'bored':        f'{EXTRACT_PATH}/Student-engagement-dataset/Not engaged/bored',
    'drowsy':       f'{EXTRACT_PATH}/Student-engagement-dataset/Not engaged/drowsy',
    'Looking Away': f'{EXTRACT_PATH}/Student-engagement-dataset/Not engaged/Looking Away',
}
COLORS = ['#1D9E75','#378ADD','#7F77DD','#BA7517','#E24B4A','#888780']
LABELS = list(SOURCE_CLASSES.keys())

# ── Count images ───────────────────────────────────────────
counts = {}
all_sizes = []
for cls, path in SOURCE_CLASSES.items():
    imgs = [f for f in os.listdir(path) if f.lower().endswith(('.jpg','.jpeg','.png'))]
    counts[cls] = len(imgs)
    # Sample 10 images for size analysis
    for f in random.sample(imgs, min(10, len(imgs))):
        try:
            with Image.open(os.path.join(path, f)) as im:
                all_sizes.append(im.size)
        except:
            pass

total    = sum(counts.values())
mean_val = total / len(counts)
labels   = list(counts.keys())
values   = list(counts.values())
engaged_total     = counts['engaged'] + counts['confused'] + counts['frustrated']
not_engaged_total = counts['bored']   + counts['drowsy']   + counts['Looking Away']

# ── Count resolutions ─────────────────────────────────────
res_counter = {}
for s in all_sizes:
    key = f'{s[0]}×{s[1]}'
    res_counter[key] = res_counter.get(key, 0) + 1

# ── FIGURE 1: Class distribution + category split ─────────
fig = plt.figure(figsize=(16, 14))
fig.patch.set_facecolor('#FAFAFA')
gs  = GridSpec(3, 3, figure=fig, hspace=0.45, wspace=0.4)

# 1A — Bar chart: images per class
ax1 = fig.add_subplot(gs[0, :2])
bars = ax1.bar(labels, values, color=COLORS, edgecolor='white', linewidth=1.2, width=0.6)
ax1.axhline(mean_val, color='#555', linestyle='--', linewidth=1.2, label=f'Mean = {mean_val:.0f}')
for bar, val in zip(bars, values):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
             str(val), ha='center', va='bottom', fontsize=11, fontweight='bold')
ax1.set_title('Number of images per class', fontsize=14, fontweight='bold', pad=10)
ax1.set_ylabel('Image count', fontsize=11)
ax1.set_ylim(0, max(values) + 60)
ax1.legend(fontsize=10)
ax1.spines[['top','right']].set_visible(False)
ax1.set_facecolor('#F7F7F7')
ax1.tick_params(axis='x', rotation=15)

# 1B — Donut: engaged vs not engaged
ax2 = fig.add_subplot(gs[0, 2])
wedge_vals  = [engaged_total, not_engaged_total]
wedge_lbls  = [f'Engaged\n{engaged_total}\n({engaged_total/total*100:.1f}%)',
               f'Not engaged\n{not_engaged_total}\n({not_engaged_total/total*100:.1f}%)']
wedges, _ = ax2.pie(wedge_vals, labels=None, colors=['#1D9E75','#E24B4A'],
                    startangle=90, wedgeprops=dict(width=0.5))
ax2.legend(wedges, wedge_lbls, loc='lower center', bbox_to_anchor=(0.5,-0.25),
           fontsize=9, frameon=False)
ax2.set_title('Category split', fontsize=14, fontweight='bold', pad=10)
ax2.text(0, 0, f'{total}\ntotal', ha='center', va='center', fontsize=11, fontweight='bold')

# 1C — Horizontal bar: class imbalance (deviation from mean)
ax3 = fig.add_subplot(gs[1, :2])
deviations = [v - mean_val for v in values]
bar_colors = ['#1D9E75' if d >= 0 else '#E24B4A' for d in deviations]
h_bars = ax3.barh(labels, deviations, color=bar_colors, edgecolor='white', linewidth=0.8)
ax3.axvline(0, color='#333', linewidth=1.0)
for bar, dev in zip(h_bars, deviations):
    xpos = dev + (2 if dev >= 0 else -2)
    ax3.text(xpos, bar.get_y() + bar.get_height()/2,
             f'{dev:+.0f}', va='center', ha='left' if dev >= 0 else 'right', fontsize=10)
ax3.set_title(f'Class imbalance — deviation from mean ({mean_val:.0f} images)', fontsize=13, fontweight='bold', pad=8)
ax3.set_xlabel('Deviation (images)', fontsize=10)
ax3.spines[['top','right']].set_visible(False)
ax3.set_facecolor('#F7F7F7')
pos_patch = mpatches.Patch(color='#1D9E75', label='Above mean')
neg_patch = mpatches.Patch(color='#E24B4A', label='Below mean')
ax3.legend(handles=[pos_patch, neg_patch], fontsize=9, frameon=False)

# 1D — Pie: resolution split
ax4 = fig.add_subplot(gs[1, 2])
if res_counter:
    res_labels = list(res_counter.keys())
    res_vals   = list(res_counter.values())
    ax4.pie(res_vals, labels=res_labels, autopct='%1.0f%%',
            colors=['#7F77DD','#5DCAA5'], startangle=90,
            textprops={'fontsize': 9})
ax4.set_title('Image resolutions', fontsize=13, fontweight='bold', pad=8)

# 1E — Stacked bar: train/val/test per class
ax5 = fig.add_subplot(gs[2, :])
train_vals = [round(v * 0.70) for v in values]
val_vals   = [round(v * 0.15) for v in values]
test_vals  = [v - t - va for v, t, va in zip(values, train_vals, val_vals)]
x = np.arange(len(labels))
w = 0.55
b1 = ax5.bar(x, train_vals, w, label='Train (70%)', color='#378ADD', edgecolor='white')
b2 = ax5.bar(x, val_vals,   w, bottom=train_vals, label='Validation (15%)', color='#EF9F27', edgecolor='white')
b3 = ax5.bar(x, test_vals,  w,
             bottom=[t+v for t,v in zip(train_vals, val_vals)],
             label='Test (15%)', color='#E24B4A', edgecolor='white')
for i, (t, va, te) in enumerate(zip(train_vals, val_vals, test_vals)):
    ax5.text(i, t/2,          str(t),  ha='center', va='center', fontsize=9,  color='white', fontweight='bold')
    ax5.text(i, t + va/2,     str(va), ha='center', va='center', fontsize=9,  color='white', fontweight='bold')
    ax5.text(i, t + va + te/2, str(te), ha='center', va='center', fontsize=9, color='white', fontweight='bold')
ax5.set_xticks(x)
ax5.set_xticklabels(labels, fontsize=11)
ax5.set_title('Train / validation / test split per class', fontsize=14, fontweight='bold', pad=10)
ax5.set_ylabel('Images', fontsize=11)
ax5.legend(fontsize=10, loc='upper right')
ax5.spines[['top','right']].set_visible(False)
ax5.set_facecolor('#F7F7F7')

fig.suptitle('Student Engagement Dataset — Visual Analysis', fontsize=17, fontweight='bold', y=1.01)
plt.savefig('/content/dataset_analysis_1.png', dpi=130, bbox_inches='tight', facecolor='#FAFAFA')
plt.show()
print('✅ Figure 1 saved: /content/dataset_analysis_1.png')


# ── FIGURE 2: Sample images from each class ───────────────
fig2, axes = plt.subplots(2, 6, figsize=(18, 7))
fig2.patch.set_facecolor('#FAFAFA')
fig2.suptitle('Sample images — 2 per class', fontsize=15, fontweight='bold')

for col, (cls, path) in enumerate(SOURCE_CLASSES.items()):
    imgs = [f for f in os.listdir(path) if f.lower().endswith(('.jpg','.jpeg','.png'))]
    sampled = random.sample(imgs, 2)
    for row, img_file in enumerate(sampled):
        img = Image.open(os.path.join(path, img_file)).convert('RGB')
        img = img.resize((224, 224))
        axes[row][col].imshow(img)
        if row == 0:
            axes[row][col].set_title(cls, fontsize=11, fontweight='bold',
                                     color=COLORS[col], pad=5)
        axes[row][col].axis('off')

plt.tight_layout()
plt.savefig('/content/dataset_analysis_2_samples.png', dpi=130, bbox_inches='tight', facecolor='#FAFAFA')
plt.show()
print('✅ Figure 2 saved: /content/dataset_analysis_2_samples.png')


# ── FIGURE 3: Pixel brightness distribution per class ─────
fig3, ax = plt.subplots(figsize=(12, 5))
fig3.patch.set_facecolor('#FAFAFA')
ax.set_facecolor('#F7F7F7')

for i, (cls, path) in enumerate(SOURCE_CLASSES.items()):
    imgs  = [f for f in os.listdir(path) if f.lower().endswith(('.jpg','.jpeg','.png'))]
    brightness = []
    for f in random.sample(imgs, min(30, len(imgs))):
        try:
            img = Image.open(os.path.join(path, f)).convert('L')  # grayscale
            brightness.append(np.mean(np.array(img)))
        except:
            pass
    ax.hist(brightness, bins=20, alpha=0.55, color=COLORS[i], label=cls, edgecolor='white')

ax.set_title('Pixel brightness distribution per class (grayscale mean)', fontsize=14, fontweight='bold')
ax.set_xlabel('Mean pixel brightness (0=black, 255=white)', fontsize=11)
ax.set_ylabel('Frequency', fontsize=11)
ax.legend(fontsize=10, frameon=False)
ax.spines[['top','right']].set_visible(False)

plt.tight_layout()
plt.savefig('/content/dataset_analysis_3_brightness.png', dpi=130, bbox_inches='tight', facecolor='#FAFAFA')
plt.show()
print('✅ Figure 3 saved: /content/dataset_analysis_3_brightness.png')


# ── FIGURE 4: Percentage table summary ────────────────────
fig4, ax4 = plt.subplots(figsize=(11, 3.5))
fig4.patch.set_facecolor('#FAFAFA')
ax4.axis('off')

col_labels = ['Class', 'Category', 'Total', '% of dataset', 'Train', 'Val', 'Test']
table_data = []
for cls, val in counts.items():
    cat   = 'Engaged' if cls in ['engaged','confused','frustrated'] else 'Not Engaged'
    train = round(val * 0.70)
    v     = round(val * 0.15)
    t     = val - train - v
    table_data.append([cls, cat, str(val), f'{val/total*100:.1f}%', str(train), str(v), str(t)])

table = ax4.table(cellText=table_data, colLabels=col_labels,
                  cellLoc='center', loc='center')
table.auto_set_font_size(False)
table.set_fontsize(11)
table.scale(1.2, 1.8)

# Style header row
for j in range(len(col_labels)):
    table[0, j].set_facecolor('#378ADD')
    table[0, j].set_text_props(color='white', fontweight='bold')

# Color code category column
cat_colors = {'Engaged': '#E1F5EE', 'Not Engaged': '#FAECE7'}
for i, row in enumerate(table_data):
    for j in range(len(col_labels)):
        if row[1] in cat_colors:
            table[i+1, j].set_facecolor(cat_colors[row[1]])

ax4.set_title('Dataset summary table', fontsize=14, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('/content/dataset_analysis_4_table.png', dpi=130, bbox_inches='tight', facecolor='#FAFAFA')
plt.show()
print('✅ Figure 4 saved: /content/dataset_analysis_4_table.png')


# ── Print text summary ────────────────────────────────────
print('\n' + '='*55)
print('       DATASET SUMMARY')
print('='*55)
print(f'  Total images   : {total}')
print(f'  Classes        : {len(counts)}')
print(f'  Mean per class : {mean_val:.0f}')
print(f'  Most images    : {max(counts, key=counts.get)} ({max(counts.values())})')
print(f'  Least images   : {min(counts, key=counts.get)} ({min(counts.values())})')
print(f'  Engaged total  : {engaged_total}  ({engaged_total/total*100:.1f}%)')
print(f'  Not Engaged    : {not_engaged_total}  ({not_engaged_total/total*100:.1f}%)')
print(f'  Resolutions    : {list(set(f"{s[0]}x{s[1]}" for s in all_sizes))}')
print('='*55)
print('\n✅ All 4 figures saved to /content/')

"""## ✅ STEP 3 — Split into Train / Val / Test (70 / 15 / 15)"""

# Source folders — exactly matching your zip structure
SOURCE_CLASSES = {
    'engaged':      f'{EXTRACT_PATH}/Student-engagement-dataset/Engaged/engaged',
    'confused':     f'{EXTRACT_PATH}/Student-engagement-dataset/Engaged/confused',
    'frustrated':   f'{EXTRACT_PATH}/Student-engagement-dataset/Engaged/frustrated',
    'bored':        f'{EXTRACT_PATH}/Student-engagement-dataset/Not engaged/bored',
    'drowsy':       f'{EXTRACT_PATH}/Student-engagement-dataset/Not engaged/drowsy',
    'Looking Away': f'{EXTRACT_PATH}/Student-engagement-dataset/Not engaged/Looking Away',
}

DATASET_PATH = '/content/dataset'
TRAIN_R, VAL_R = 0.70, 0.15       # 70% train · 15% val · 15% test
random.seed(42)                    # fixed seed → same split every run

print('📁 Splitting dataset…')
print('=' * 56)
total = {'train': 0, 'val': 0, 'test': 0}

for cls, src in SOURCE_CLASSES.items():
    # Verify the source folder exists
    if not os.path.exists(src):
        print(f'❌ MISSING: {src}')
        continue

    imgs = [f for f in os.listdir(src)
            if f.lower().endswith(('.jpg','.jpeg','.png'))]
    random.shuffle(imgs)

    n  = len(imgs)
    t1 = int(n * TRAIN_R)           # end of train slice
    t2 = int(n * (TRAIN_R + VAL_R)) # end of val slice

    splits = {'train': imgs[:t1], 'val': imgs[t1:t2], 'test': imgs[t2:]}

    for split, files in splits.items():
        dest = os.path.join(DATASET_PATH, split, cls)
        os.makedirs(dest, exist_ok=True)
        for f in files:
            shutil.copy2(os.path.join(src, f), os.path.join(dest, f))
        total[split] += len(files)

    tr, va, te = len(splits['train']), len(splits['val']), len(splits['test'])
    print(f'✅ {cls:15s} Train:{tr:4d}  Val:{va:4d}  Test:{te:4d}')

print('=' * 56)
print(f'   {"TOTAL":15s} Train:{total["train"]:4d}  Val:{total["val"]:4d}  Test:{total["test"]:4d}')
print('\n✅ Split complete!')

"""## ✅ STEP 4 — Load & Augment Images"""

IMG_SIZE   = 224    # MobileNetV2 native size
BATCH_SIZE = 32
NUM_CLASSES = 6

# ─── Training generator — WITH augmentation ───────────────────────────────
# NO rescale here! preprocess_input() inside the model handles normalisation.
train_gen = ImageDataGenerator(
    rotation_range     = 20,          # rotate up to 20°
    width_shift_range  = 0.15,        # shift left/right
    height_shift_range = 0.15,        # shift up/down
    zoom_range         = 0.15,        # zoom in/out
    horizontal_flip    = True,        # mirror image
    brightness_range   = [0.7, 1.3],  # vary brightness
    shear_range        = 0.1,
    fill_mode          = 'nearest'
)

# ─── Val / Test generator — no augmentation ───────────────────────────────
plain_gen = ImageDataGenerator()     # no rescale, no augmentation

train_data = train_gen.flow_from_directory(
    f'{DATASET_PATH}/train',
    target_size = (IMG_SIZE, IMG_SIZE),
    batch_size  = BATCH_SIZE,
    class_mode  = 'categorical',
    shuffle     = True
)
val_data = plain_gen.flow_from_directory(
    f'{DATASET_PATH}/val',
    target_size = (IMG_SIZE, IMG_SIZE),
    batch_size  = BATCH_SIZE,
    class_mode  = 'categorical',
    shuffle     = False
)
test_data = plain_gen.flow_from_directory(
    f'{DATASET_PATH}/test',
    target_size = (IMG_SIZE, IMG_SIZE),
    batch_size  = BATCH_SIZE,
    class_mode  = 'categorical',
    shuffle     = False
)

CLASS_LABELS = list(train_data.class_indices.keys())
print('Classes:', CLASS_LABELS)
print(f'Train:{train_data.n}  Val:{val_data.n}  Test:{test_data.n}')
print('✅ Data loaders ready')

# ── Quick look at sample images ──────────────────────────────────────────
batch_imgs, batch_labels = next(train_data)
idx2cls = {v: k for k, v in train_data.class_indices.items()}

fig, axes = plt.subplots(2, 6, figsize=(18, 6))
shown, col = {}, 0
for img, lbl in zip(batch_imgs, batch_labels):
    cls = idx2cls[np.argmax(lbl)]
    if cls not in shown:
        shown[cls] = img
    if len(shown) == 6:
        break

for col, (cls, img) in enumerate(shown.items()):
    # img pixels are 0-255 here (no rescale applied by generator)
    axes[0][col].imshow(img.astype('uint8'))
    axes[0][col].set_title(cls, fontweight='bold')
    axes[0][col].axis('off')
    axes[1][col].axis('off')

plt.suptitle('One sample per class', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()
print('✅ Sample images shown')

"""## ✅ STEP 5 — Build MobileNetV2 Model"""

# ── Load MobileNetV2 pre-trained on ImageNet ─────────────────────────────
base = MobileNetV2(
    weights      = 'imagenet',          # use ImageNet knowledge
    include_top  = False,               # remove original classifier
    input_shape  = (IMG_SIZE, IMG_SIZE, 3)
)

# Freeze first 100 layers (basic edge/colour detectors — already good)
# Train layers 100+ so the model learns face-expression features
for layer in base.layers[:100]:
    layer.trainable = False
for layer in base.layers[100:]:
    layer.trainable = True

frozen    = sum(1 for l in base.layers if not l.trainable)
trainable = sum(1 for l in base.layers if l.trainable)
print(f'MobileNetV2 — Frozen: {frozen}  Trainable: {trainable}')

# ── Build full model ──────────────────────────────────────────────────────
inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))

# preprocess_input converts 0-255 pixels to what MobileNetV2 expects (-1 to 1)
x = preprocess_input(inputs)

x = base(x, training=False)              # run through MobileNetV2
x = layers.GlobalAveragePooling2D()(x)   # flatten feature maps
x = layers.BatchNormalization()(x)       # stabilise training
x = layers.Dense(512, activation='relu')(x)
x = layers.Dropout(0.5)(x)              # 50% dropout to prevent overfitting
x = layers.Dense(256, activation='relu')(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(NUM_CLASSES, activation='softmax')(x)  # 6 class output

model = Model(inputs, outputs)

model.compile(
    optimizer = keras.optimizers.Adam(learning_rate=1e-4),
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy']
)

print(f'Total parameters : {model.count_params():,}')
print('✅ MobileNetV2 model ready!')

# ── Sanity check before training ─────────────────────────────────────────
# Predictions should be spread across different classes, not all the same
sample_imgs, sample_lbls = next(train_data)
preds = model.predict(sample_imgs[:6], verbose=0)

print('🔍 Sanity check — 6 predictions before training:')
print(f'{"True Class":15s}  {"Pred Class":15s}  Confidence')
print('-' * 48)
for lbl, pred in zip(sample_lbls[:6], preds):
    true_cls = CLASS_LABELS[np.argmax(lbl)]
    pred_cls = CLASS_LABELS[np.argmax(pred)]
    conf     = np.max(pred) * 100
    print(f'{true_cls:15s}  {pred_cls:15s}  {conf:.1f}%')

print('\n✅ If Pred Classes above are varied → model is fine, proceed to training')
print('❌ If ALL predictions are the same class → restart runtime and re-run')

"""## ✅ STEP 6 — Train the Model"""

callbacks = [
    # Save best model automatically
    ModelCheckpoint(
        '/content/best_model.keras',
        monitor        = 'val_accuracy',
        save_best_only = True,
        mode           = 'max',
        verbose        = 1
    ),
    # Stop training if val_accuracy stops improving for 12 epochs
    EarlyStopping(
        monitor             = 'val_accuracy',
        patience            = 12,
        restore_best_weights= True,
        verbose             = 1
    ),
    # Halve learning rate if val_loss stalls for 4 epochs
    ReduceLROnPlateau(
        monitor  = 'val_loss',
        factor   = 0.5,
        patience = 4,
        min_lr   = 1e-7,
        verbose  = 1
    )
]

print('🚀 Training MobileNetV2…')
print('Expected: accuracy > 50% by epoch 5, final ~75-85%')
print('=' * 60)

history = model.fit(
    train_data,
    epochs          = 100,
    validation_data = val_data,
    callbacks       = callbacks,
    verbose         = 1
)

best_val = max(history.history['val_accuracy'])
print(f'\n🎯 Best Validation Accuracy: {best_val*100:.2f}%')

"""## ✅ STEP 7 — Plot Results & Confusion Matrix"""

# ── Accuracy & Loss curves ────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(15, 5))
epochs_range = range(1, len(history.history['accuracy']) + 1)

# Accuracy
axes[0].plot(epochs_range, history.history['accuracy'],     'b-o', ms=4, label='Train')
axes[0].plot(epochs_range, history.history['val_accuracy'], 'r-o', ms=4, label='Val')
axes[0].set_title('Accuracy', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Accuracy')
axes[0].legend(); axes[0].grid(alpha=0.3)

# Loss
axes[1].plot(epochs_range, history.history['loss'],     'b-o', ms=4, label='Train')
axes[1].plot(epochs_range, history.history['val_loss'], 'r-o', ms=4, label='Val')
axes[1].set_title('Loss', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Loss')
axes[1].legend(); axes[1].grid(alpha=0.3)

plt.suptitle('MobileNetV2 — Training History', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig('/content/training_curves.png', dpi=100)
plt.show()
print('✅ Training curves saved')

# ── Evaluate on Test set ──────────────────────────────────────────────────
model = keras.models.load_model('/content/best_model.keras')

test_loss, test_acc = model.evaluate(test_data, verbose=1)
print(f'\n🎯 Test Accuracy : {test_acc*100:.2f}%')
print(f'📉 Test Loss     : {test_loss:.4f}')

# ── Per-class report & Confusion Matrix ──────────────────────────────────
test_data.reset()
preds       = np.argmax(model.predict(test_data, verbose=1), axis=1)
true_labels = test_data.classes

print('\n📋 Classification Report:')
print('=' * 60)
print(classification_report(true_labels, preds, target_names=CLASS_LABELS))

# Confusion matrix heatmap
cm = confusion_matrix(true_labels, preds)
plt.figure(figsize=(9, 7))
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=CLASS_LABELS, yticklabels=CLASS_LABELS,
    linewidths=0.5
)
plt.title('Confusion Matrix\n(rows = actual · cols = predicted)',
          fontsize=13, fontweight='bold')
plt.ylabel('Actual'); plt.xlabel('Predicted')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('/content/confusion_matrix.png', dpi=100)
plt.show()
print('✅ Confusion matrix saved')

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import numpy as np

# 1. Calculate overall global metrics (Macro Averaged)
accuracy = accuracy_score(true_labels, preds)
precision_macro = precision_score(true_labels, preds, average='macro')
recall_macro = recall_score(true_labels, preds, average='macro')
f1_macro = f1_score(true_labels, preds, average='macro')

# 2. Extract Specificity class-by-class from the confusion matrix
cm = confusion_matrix(true_labels, preds)
specificity_per_class = []

for i in range(len(CLASS_LABELS)):
    tp = cm[i, i]
    fn = np.sum(cm[i, :]) - tp
    fp = np.sum(cm[:, i]) - tp
    tn = np.sum(cm) - tp - fp - fn

    # Avoid dividing by zero if a class has no negative samples/false positives
    spec = tn / (tn + fp) if (tn + fp) > 0 else 0
    specificity_per_class.append(spec)

# Calculate the average specificity across all 6 classes
specificity_macro = np.mean(specificity_per_class)

# 3. Print out the Summary Report
print('\n📈 Summary Evaluation Metrics (Macro Average):')
print('=' * 65)
print(f"✨ Overall Accuracy: {accuracy:.4f}  ({accuracy*100:.2f}%)")
print(f"🎯 Precision:        {precision_macro:.4f}  ({precision_macro*100:.2f}%)")
print(f"🧪 Recall (Sens.):   {recall_macro:.4f}  ({recall_macro*100:.2f}%)")
print(f"🧬 F1-Score:         {f1_macro:.4f}  ({f1_macro*100:.2f}%)")
print(f"🛡️ Specificity:     {specificity_macro:.4f}  ({specificity_macro*100:.2f}%)")
print('=' * 65)

# 4. Print detailed Per-Class Breakdown
precision_each = precision_score(true_labels, preds, average=None)
recall_each = recall_score(true_labels, preds, average=None)
f1_each = f1_score(true_labels, preds, average=None)

print('\n📊 Breakdown Table Per Class:')
print('=' * 75)
print(f"{'Class Name':<15} | {'Precision':<9} | {'Recall':<8} | {'F1-Score':<8} | {'Specificity':<11}")
print('-' * 75)
for i, class_name in enumerate(CLASS_LABELS):
    print(f"{class_name:<15} | {precision_each[i]:.4f}    | {recall_each[i]:.4f} | {f1_each[i]:.4f} | {specificity_per_class[i]:.4f}")
print('=' * 75)

# ── Visual prediction on random test images ───────────────────────────────
from tensorflow.keras.preprocessing.image import load_img, img_to_array

fig, axes = plt.subplots(2, 6, figsize=(20, 7))
fig.suptitle('Random Test Predictions', fontsize=14, fontweight='bold')

for col, cls in enumerate(CLASS_LABELS):
    cls_folder = f'{DATASET_PATH}/test/{cls}'
    img_file   = random.choice(os.listdir(cls_folder))
    img_path   = os.path.join(cls_folder, img_file)

    img       = load_img(img_path, target_size=(IMG_SIZE, IMG_SIZE))
    img_arr   = img_to_array(img)                        # 0-255
    img_input = np.expand_dims(img_arr, axis=0)          # batch dim

    pred      = model.predict(img_input, verbose=0)[0]
    pred_cls  = CLASS_LABELS[np.argmax(pred)]
    conf      = np.max(pred) * 100
    correct   = pred_cls == cls

    axes[0][col].imshow(img)
    axes[0][col].set_title(
        f'True: {cls}\nPred: {pred_cls}\n{conf:.0f}%',
        fontsize=8,
        color='green' if correct else 'red',
        fontweight='bold'
    )
    axes[0][col].axis('off')
    axes[1][col].axis('off')

plt.tight_layout()
plt.savefig('/content/test_predictions.png', dpi=100)
plt.show()
print(' Green title = correct  |  Red title = wrong')

# --- GRAPH 1: TRAINING HISTORY ---
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Accuracy Curve
ax1.plot(history.history['accuracy'], label='Training Accuracy', linewidth=2, color='#1f77b4')
ax1.plot(history.history['val_accuracy'], label='Validation Accuracy', linewidth=2, linestyle='--', color='#ff7f0e')
ax1.set_title('Model Accuracy History', fontsize=11, fontweight='bold')
ax1.set_xlabel('Epochs')
ax1.set_ylabel('Accuracy')
ax1.legend(loc='lower right')
ax1.grid(True, linestyle=':', alpha=0.6)

# Loss Curve
ax2.plot(history.history['loss'], label='Training Loss', linewidth=2, color='#1f77b4')
ax2.plot(history.history['val_loss'], label='Validation Loss', linewidth=2, linestyle='--', color='#ff7f0e')
ax2.set_title('Model Loss History', fontsize=11, fontweight='bold')
ax2.set_xlabel('Epochs')
ax2.set_ylabel('Loss')
ax2.legend(loc='upper right')
ax2.grid(True, linestyle=':', alpha=0.6)

plt.tight_layout()
plt.savefig('/content/IEEE_training_history.png', dpi=300, bbox_inches='tight')
plt.show()
print("💾 Saved: /content/IEEE_training_history.png")

"""# 📊 CONFUSION MATRIX — Full Visualization"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from tensorflow import keras

# ── Get predictions ───────────────────────────────────────
model = keras.models.load_model('/content/best_model.keras')

test_data.reset()
y_pred_probs = model.predict(test_data, verbose=1)
y_pred       = np.argmax(y_pred_probs, axis=1)
y_true       = test_data.classes
CLASS_NAMES  = list(test_data.class_indices.keys())

# ── Compute confusion matrix ──────────────────────────────
cm      = confusion_matrix(y_true, y_pred)
cm_norm = cm.astype('float') / cm.sum(axis=1, keepdims=True) * 100  # row %

# ══════════════════════════════════════════════════════════
# PLOT 1 — Raw count confusion matrix
# ══════════════════════════════════════════════════════════
fig1, ax1 = plt.subplots(figsize=(10, 8))
fig1.patch.set_facecolor('#FAFAFA')

sns.heatmap(
    cm,
    annot=True,
    fmt='d',                          # integer counts
    cmap='Blues',
    linewidths=0.5,
    linecolor='white',
    xticklabels=CLASS_NAMES,
    yticklabels=CLASS_NAMES,
    ax=ax1,
    annot_kws={'size': 13, 'weight': 'bold'},
    cbar_kws={'label': 'Number of predictions', 'shrink': 0.82}
)

# Highlight diagonal (correct predictions) with a green border
for i in range(len(CLASS_NAMES)):
    ax1.add_patch(plt.Rectangle(
        (i, i), 1, 1,
        fill=False, edgecolor='#1D9E75', lw=2.5
    ))

ax1.set_title('Confusion matrix — Raw counts\n(green border = correct predictions)',
              fontsize=14, fontweight='bold', pad=15)
ax1.set_ylabel('Actual label',    fontsize=12, labelpad=10)
ax1.set_xlabel('Predicted label', fontsize=12, labelpad=10)
ax1.tick_params(axis='x', rotation=30, labelsize=11)
ax1.tick_params(axis='y', rotation=0,  labelsize=11)

plt.tight_layout()
plt.savefig('/content/confusion_matrix_counts.png', dpi=130,
            bbox_inches='tight', facecolor='#FAFAFA')
plt.show()
print('✅ Saved: /content/confusion_matrix_counts.png')


# ══════════════════════════════════════════════════════════
# PLOT 2 — Normalised confusion matrix (row %)
# ══════════════════════════════════════════════════════════
fig2, ax2 = plt.subplots(figsize=(10, 8))
fig2.patch.set_facecolor('#FAFAFA')

sns.heatmap(
    cm_norm,
    annot=True,
    fmt='.1f',                        # one decimal percentage
    cmap='Greens',
    linewidths=0.5,
    linecolor='white',
    xticklabels=CLASS_NAMES,
    yticklabels=CLASS_NAMES,
    ax=ax2,
    vmin=0, vmax=100,
    annot_kws={'size': 12, 'weight': 'bold'},
    cbar_kws={'label': '% of actual class', 'shrink': 0.82}
)

# Add % symbol inside each cell
for text in ax2.texts:
    text.set_text(text.get_text() + '%')

# Highlight diagonal
for i in range(len(CLASS_NAMES)):
    ax2.add_patch(plt.Rectangle(
        (i, i), 1, 1,
        fill=False, edgecolor='#185FA5', lw=2.5
    ))

ax2.set_title('Confusion matrix — Normalised (%)\n(blue border = correct predictions)',
              fontsize=14, fontweight='bold', pad=15)
ax2.set_ylabel('Actual label',    fontsize=12, labelpad=10)
ax2.set_xlabel('Predicted label', fontsize=12, labelpad=10)
ax2.tick_params(axis='x', rotation=30, labelsize=11)
ax2.tick_params(axis='y', rotation=0,  labelsize=11)

plt.tight_layout()
plt.savefig('/content/confusion_matrix_normalised.png', dpi=130,
            bbox_inches='tight', facecolor='#FAFAFA')
plt.show()
print('✅ Saved: /content/confusion_matrix_normalised.png')


# ══════════════════════════════════════════════════════════
# PLOT 3 — Side by side (both in one figure)
# ══════════════════════════════════════════════════════════
fig3, (axA, axB) = plt.subplots(1, 2, figsize=(20, 8))
fig3.patch.set_facecolor('#FAFAFA')
fig3.suptitle('Confusion matrix — Student Engagement Detection',
              fontsize=16, fontweight='bold', y=1.02)

# Left: raw counts
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            linewidths=0.5, linecolor='white',
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
            ax=axA, annot_kws={'size': 12},
            cbar_kws={'shrink': 0.82})
for i in range(len(CLASS_NAMES)):
    axA.add_patch(plt.Rectangle((i,i),1,1,fill=False,edgecolor='#1D9E75',lw=2))
axA.set_title('Raw counts',       fontsize=13, fontweight='bold')
axA.set_ylabel('Actual',          fontsize=11)
axA.set_xlabel('Predicted',       fontsize=11)
axA.tick_params(axis='x', rotation=30, labelsize=10)
axA.tick_params(axis='y', rotation=0,  labelsize=10)

# Right: normalised %
sns.heatmap(cm_norm, annot=True, fmt='.1f', cmap='Greens',
            linewidths=0.5, linecolor='white',
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
            ax=axB, vmin=0, vmax=100,
            annot_kws={'size': 12},
            cbar_kws={'shrink': 0.82})
for text in axB.texts:
    text.set_text(text.get_text() + '%')
for i in range(len(CLASS_NAMES)):
    axB.add_patch(plt.Rectangle((i,i),1,1,fill=False,edgecolor='#185FA5',lw=2))
axB.set_title('Normalised (%)',   fontsize=13, fontweight='bold')
axB.set_ylabel('Actual',          fontsize=11)
axB.set_xlabel('Predicted',       fontsize=11)
axB.tick_params(axis='x', rotation=30, labelsize=10)
axB.tick_params(axis='y', rotation=0,  labelsize=10)

plt.tight_layout()
plt.savefig('/content/confusion_matrix_combined.png', dpi=130,
            bbox_inches='tight', facecolor='#FAFAFA')
plt.show()
print('✅ Saved: /content/confusion_matrix_combined.png')


# ══════════════════════════════════════════════════════════
# Print diagonal accuracy summary
# ══════════════════════════════════════════════════════════
print('\n📋 Per-class correct predictions:')
print('─' * 42)
for i, cls in enumerate(CLASS_NAMES):
    correct = cm[i, i]
    total   = cm[i].sum()
    pct     = correct / total * 100
    bar     = '█' * int(pct / 5)
    print(f'  {cls:15s} {correct:3d}/{total:3d}  {pct:5.1f}%  {bar}')
print('─' * 42)
overall = np.trace(cm) / np.sum(cm) * 100
print(f'  {"Overall":15s} {np.trace(cm):3d}/{np.sum(cm):3d}  {overall:5.1f}%')

"""## CLASS-WISE PERFORMANCE CHARTS"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from sklearn.metrics import (classification_report, confusion_matrix,
                             precision_score, recall_score, f1_score)
from tensorflow import keras
import warnings
warnings.filterwarnings('ignore')

# ── Load best saved model ─────────────────────────────────
model = keras.models.load_model('/content/best_model.keras')

# ── Get predictions ───────────────────────────────────────
test_data.reset()
y_pred_probs = model.predict(test_data, verbose=1)
y_pred       = np.argmax(y_pred_probs, axis=1)
y_true       = test_data.classes
CLASS_NAMES  = list(test_data.class_indices.keys())
COLORS       = ['#1D9E75','#378ADD','#7F77DD','#BA7517','#E24B4A','#888780']
N            = len(CLASS_NAMES)

# ── Compute per-class metrics ─────────────────────────────
precision = precision_score(y_true, y_pred, average=None)
recall    = recall_score(y_true, y_pred, average=None)
f1        = f1_score(y_true, y_pred, average=None)
overall   = np.mean(y_pred == y_true) * 100
macro_f1  = np.mean(f1)

print(f'\n🎯 Overall Accuracy : {overall:.2f}%')
print(f'📊 Macro F1 Score   : {macro_f1:.4f}')
print(f'\n📋 Full Report:\n')
print(classification_report(y_true, y_pred, target_names=CLASS_NAMES))


# ══════════════════════════════════════════════════════════
# FIGURE 1 — Precision, Recall, F1 bars + Grouped comparison
# ══════════════════════════════════════════════════════════
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.patch.set_facecolor('#FAFAFA')
fig.suptitle(f'Class-wise Performance  |  Accuracy: {overall:.1f}%  |  Macro F1: {macro_f1:.3f}',
             fontsize=15, fontweight='bold', y=1.01)

# ── 1A: Precision ─────────────────────────────────────────
ax = axes[0][0]
bars = ax.bar(CLASS_NAMES, precision, color=COLORS, edgecolor='white',
              linewidth=1, width=0.6, zorder=3)
ax.axhline(0.80, color='#EF9F27', linestyle='--', linewidth=1.5,
           label='0.80 threshold', zorder=2)
ax.axhline(np.mean(precision), color='#555', linestyle=':', linewidth=1.2,
           label=f'Mean = {np.mean(precision):.2f}', zorder=2)
for bar, val in zip(bars, precision):
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.005,
            f'{val:.2f}', ha='center', va='bottom', fontsize=10, fontweight='bold')
ax.set_title('Precision per class', fontsize=13, fontweight='bold')
ax.set_ylim(0, 1.15)
ax.set_ylabel('Precision')
ax.legend(fontsize=9, frameon=False)
ax.spines[['top','right']].set_visible(False)
ax.set_facecolor('#F7F7F7')
ax.tick_params(axis='x', rotation=20)
ax.grid(axis='y', alpha=0.3, zorder=0)

# ── 1B: Recall ────────────────────────────────────────────
ax = axes[0][1]
bars = ax.bar(CLASS_NAMES, recall, color=COLORS, edgecolor='white',
              linewidth=1, width=0.6, zorder=3)
ax.axhline(0.80, color='#EF9F27', linestyle='--', linewidth=1.5,
           label='0.80 threshold', zorder=2)
ax.axhline(np.mean(recall), color='#555', linestyle=':', linewidth=1.2,
           label=f'Mean = {np.mean(recall):.2f}', zorder=2)
for bar, val in zip(bars, recall):
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.005,
            f'{val:.2f}', ha='center', va='bottom', fontsize=10, fontweight='bold')
ax.set_title('Recall per class', fontsize=13, fontweight='bold')
ax.set_ylim(0, 1.15)
ax.set_ylabel('Recall')
ax.legend(fontsize=9, frameon=False)
ax.spines[['top','right']].set_visible(False)
ax.set_facecolor('#F7F7F7')
ax.tick_params(axis='x', rotation=20)
ax.grid(axis='y', alpha=0.3, zorder=0)

# ── 1C: F1-score horizontal ───────────────────────────────
ax = axes[1][0]
sorted_idx = np.argsort(f1)
s_names  = [CLASS_NAMES[i] for i in sorted_idx]
s_f1     = [f1[i]          for i in sorted_idx]
s_colors = [COLORS[i]      for i in sorted_idx]
h_bars = ax.barh(s_names, s_f1, color=s_colors, edgecolor='white',
                 linewidth=1, height=0.6, zorder=3)
ax.axvline(np.mean(f1), color='#555', linestyle=':', linewidth=1.2,
           label=f'Mean F1 = {np.mean(f1):.2f}', zorder=2)
for bar, val in zip(h_bars, s_f1):
    ax.text(bar.get_width()+0.005, bar.get_y()+bar.get_height()/2,
            f'{val:.2f}', va='center', fontsize=10, fontweight='bold')
ax.set_title('F1-score per class (sorted)', fontsize=13, fontweight='bold')
ax.set_xlim(0, 1.15)
ax.set_xlabel('F1 score')
ax.legend(fontsize=9, frameon=False)
ax.spines[['top','right']].set_visible(False)
ax.set_facecolor('#F7F7F7')
ax.grid(axis='x', alpha=0.3, zorder=0)

# ── 1D: Grouped bar — Precision / Recall / F1 ────────────
ax = axes[1][1]
x  = np.arange(N)
w  = 0.25
b1 = ax.bar(x - w, precision, w, label='Precision', color='#378ADD',
            edgecolor='white', zorder=3)
b2 = ax.bar(x,     recall,    w, label='Recall',    color='#7F77DD',
            edgecolor='white', zorder=3)
b3 = ax.bar(x + w, f1,        w, label='F1 score',  color='#1D9E75',
            edgecolor='white', zorder=3)
ax.set_xticks(x)
ax.set_xticklabels(CLASS_NAMES, rotation=20, fontsize=9)
ax.set_title('Precision vs recall vs F1', fontsize=13, fontweight='bold')
ax.set_ylim(0, 1.15)
ax.set_ylabel('Score')
ax.legend(fontsize=9, frameon=False, loc='lower right')
ax.spines[['top','right']].set_visible(False)
ax.set_facecolor('#F7F7F7')
ax.grid(axis='y', alpha=0.3, zorder=0)

plt.tight_layout()
plt.savefig('/content/classwise_performance_1.png', dpi=130,
            bbox_inches='tight', facecolor='#FAFAFA')
plt.show()
print('✅ Figure 1 saved')


# ══════════════════════════════════════════════════════════
# FIGURE 2 — Confusion matrix (count + normalised side by side)
# ══════════════════════════════════════════════════════════
cm      = confusion_matrix(y_true, y_pred)
cm_norm = cm.astype('float') / cm.sum(axis=1, keepdims=True)

fig2, axes2 = plt.subplots(1, 2, figsize=(18, 7))
fig2.patch.set_facecolor('#FAFAFA')
fig2.suptitle('Confusion matrix', fontsize=15, fontweight='bold')

for ax2, data, fmt, title, cmap in zip(
        axes2,
        [cm, cm_norm],
        ['d', '.2f'],
        ['Raw counts', 'Normalised (row %)'],
        ['Blues', 'Greens']):

    mask_diag = np.zeros_like(data, dtype=bool)
    np.fill_diagonal(mask_diag, True)

    sns.heatmap(data, annot=True, fmt=fmt, ax=ax2,
                cmap=cmap, linewidths=0.5, linecolor='white',
                xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
                annot_kws={'size': 11, 'weight': 'bold'},
                cbar_kws={'shrink': 0.8})
    ax2.set_title(title, fontsize=13, fontweight='bold', pad=10)
    ax2.set_ylabel('Actual label',    fontsize=11)
    ax2.set_xlabel('Predicted label', fontsize=11)
    ax2.tick_params(axis='x', rotation=30, labelsize=10)
    ax2.tick_params(axis='y', rotation=0,  labelsize=10)

plt.tight_layout()
plt.savefig('/content/classwise_performance_2_confusion.png', dpi=130,
            bbox_inches='tight', facecolor='#FAFAFA')
plt.show()
print('✅ Figure 2 saved')


# ══════════════════════════════════════════════════════════
# FIGURE 3 — Per-class confidence distribution
# ══════════════════════════════════════════════════════════
fig3, axes3 = plt.subplots(2, 3, figsize=(16, 9))
fig3.patch.set_facecolor('#FAFAFA')
fig3.suptitle('Prediction confidence distribution per class',
              fontsize=15, fontweight='bold')

for idx, (ax3, cls) in enumerate(zip(axes3.flat, CLASS_NAMES)):
    mask        = y_true == idx
    correct     = y_pred[mask] == idx
    wrong       = ~correct
    conf_vals   = y_pred_probs[mask, idx]

    if correct.sum() > 0:
        ax3.hist(conf_vals[correct], bins=15, alpha=0.7,
                 color=COLORS[idx], label=f'Correct ({correct.sum()})', edgecolor='white')
    if wrong.sum() > 0:
        ax3.hist(conf_vals[wrong], bins=15, alpha=0.5,
                 color='#E24B4A', label=f'Wrong ({wrong.sum()})', edgecolor='white')

    ax3.set_title(cls, fontsize=12, fontweight='bold', color=COLORS[idx])
    ax3.set_xlabel('Confidence score', fontsize=9)
    ax3.set_ylabel('Count', fontsize=9)
    ax3.legend(fontsize=8, frameon=False)
    ax3.spines[['top','right']].set_visible(False)
    ax3.set_facecolor('#F7F7F7')
    ax3.set_xlim(0, 1)

plt.tight_layout()
plt.savefig('/content/classwise_performance_3_confidence.png', dpi=130,
            bbox_inches='tight', facecolor='#FAFAFA')
plt.show()
print('✅ Figure 3 saved')


# ══════════════════════════════════════════════════════════
# FIGURE 4 — Misclassification heatmap (what gets confused with what)
# ══════════════════════════════════════════════════════════
fig4, ax4 = plt.subplots(figsize=(9, 7))
fig4.patch.set_facecolor('#FAFAFA')

cm_no_diag = cm.copy().astype(float)
np.fill_diagonal(cm_no_diag, 0)   # hide correct predictions to highlight errors

sns.heatmap(cm_no_diag, annot=True, fmt='.0f', ax=ax4,
            cmap='Reds', linewidths=0.5, linecolor='white',
            xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
            annot_kws={'size': 12, 'weight': 'bold'},
            cbar_kws={'shrink': 0.8})
ax4.set_title('Misclassification map (correct predictions removed)',
              fontsize=13, fontweight='bold', pad=10)
ax4.set_ylabel('Actual label',    fontsize=11)
ax4.set_xlabel('Predicted label', fontsize=11)
ax4.tick_params(axis='x', rotation=30, labelsize=10)
ax4.tick_params(axis='y', rotation=0,  labelsize=10)

plt.tight_layout()
plt.savefig('/content/classwise_performance_4_misclassification.png', dpi=130,
            bbox_inches='tight', facecolor='#FAFAFA')
plt.show()
print('✅ Figure 4 saved')


# ══════════════════════════════════════════════════════════
# FIGURE 5 — Per-class accuracy bar
# ══════════════════════════════════════════════════════════
per_class_acc = cm.diagonal() / cm.sum(axis=1) * 100

fig5, ax5 = plt.subplots(figsize=(11, 5))
fig5.patch.set_facecolor('#FAFAFA')
bars5 = ax5.bar(CLASS_NAMES, per_class_acc, color=COLORS,
                edgecolor='white', linewidth=1, width=0.6, zorder=3)
ax5.axhline(overall, color='#555', linestyle='--', linewidth=1.5,
            label=f'Overall accuracy = {overall:.1f}%', zorder=2)
for bar, val in zip(bars5, per_class_acc):
    ax5.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.5,
             f'{val:.1f}%', ha='center', va='bottom',
             fontsize=11, fontweight='bold')
ax5.set_title('Per-class accuracy', fontsize=14, fontweight='bold')
ax5.set_ylabel('Accuracy (%)')
ax5.set_ylim(0, 115)
ax5.legend(fontsize=10, frameon=False)
ax5.spines[['top','right']].set_visible(False)
ax5.set_facecolor('#F7F7F7')
ax5.tick_params(axis='x', rotation=15)
ax5.grid(axis='y', alpha=0.3, zorder=0)

plt.tight_layout()
plt.savefig('/content/classwise_performance_5_accuracy.png', dpi=130,
            bbox_inches='tight', facecolor='#FAFAFA')
plt.show()